version: "3"
services:
  febiobase:
    build:
      context: ./infrastructure
      dockerfile: DockerfileBase
    image: febiosoftware/febiobase:ubuntu-22.04
    working_dir: /FEBio
    volumes:
      - ./:/FEBio

  febio: &default
    build:
      context: ./infrastructure
    image: febiosoftware/febio:ubuntu-22.04
    working_dir: /FEBio
    volumes:
      - ./:/FEBio

  febio-dev:
    <<: *default
    container_name: febio-dev
    command: sleep infinity

  febio-build:
    <<: *default
    container_name: febio-build
    command: ci/linux/build.sh

  febio-tests:
    <<: *default
    container_name: febio-tests
    command: ci/linux/test.sh

  febio-runtime:
    build:
      context: .
      dockerfile: infrastructure/DockerfileRuntime
    image: febiosoftware/febio-runtime:ubuntu-22.04
    working_dir: /FEBio
    volumes:
      - ./TestSuite/:/FEBio/TestSuite
