name: 'Run tests'
description: 'Creates SDK and Uploads artifacts'
inputs:
  shell:
    require: false
    type: string
  package-name:
    required: true
    type: string
  package-sdk:
    default: false
    required: false
    type: boolean
  os:
    required: true
    type: string
  arch:
    required: true
    type: string
  git-tag:
    required: true
    type: string
  aws-access-key-id:
    required: true
    type: string
  aws-secret-access-key:
    required: true
    type: string
  aws-region:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Download SDK
      if: ${{ inputs.package-sdk }}
      uses: actions/download-artifact@v3
      with:
        name: ${{inputs.package-name}}-sdk-${{inputs.os}}-${{inputs.arch}}
        path: |
          artifacts/febio-sdk
    - name: Download febio
      uses: actions/download-artifact@v3
      with:
        name: ${{inputs.package-name}}-${{inputs.os}}-${{inputs.arch}}
        path: |
          artifacts/febio
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Publish to S3
      shell: ${{inputs.shell}}
      env:
        BUCKET_NAME: ${{input.package-name}-packages
        OS: ${{inputs.os}}
        REF_NAME: ${{ github.ref_name}}
        PACKAGE_NAME: febio
        GIT_TAG: ${{ inputs.git_tag }}
      run: |
        ci/${{inputs.os}}/publish-to-s3.sh
