on:
  push:
    branches: [ ci/* ]
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/linux-reusable.yml@reusable-worfklow-linux
    with:
      runTests: ${{ inputs.runTests && true || false }}
      package-name: febio4
      package-sdk: true
    secrets: inherit
