on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-sdk:
        default: false
        required: false
        type: boolean
      aws-region:
        default: us-east-1
        required: false
        type: string
      os:
        default: macOS
        required: false
        type: string
      arch:
        default: X64
        required: false
        type: string
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
    secrets:
      ssh-user:
        required: true
      ssh-key:
        required: true
      ssh-host:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  build:
    name: Clone and build
    runs-on: self-hosted
    outputs:
      git_describe: ${{ steps.git-describe.outputs.git_describe }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: git-describe
        run: |
          echo "git_describe=$(git describe --tags)" >> "$GITHUB_OUTPUT"
          #      - name: Build
          #        uses: febiosoftware/FEBio/.github/actions/build.yml
          #        with:
          #          package-name: ${{ inputs.package-name }} 
          #          script: ci/${{inputs.os}}/build.sh
          #          os: ${{inputs.os}}
          #          arch: ${{inputs.arch}}

# tests:
#   if: ${{inputs.runTests}}
#   name: Run test suite
#   needs:
#     - build
#   runs-on: self-hosted
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#         submodules: 'true'
#     - uses: actions/download-artifact@v3
#       with:
#         name: febio4-${{runner.os}}-${{runner.arch}}
#         path: |
#           cmbuild
#     - name: Run test suite
#       run: |
#         ci/macos/test.sh
#     - name: Upload Artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: testsuite-${{runner.os}}-${{runner.arch}}-logs
#         path: |
#           TestSuite/Verify3/*.log
#           TestSuite/Logs*.txt
# repo-artifacts:
#   name: Upload artifacts to repo
#   needs:
#     - build # required to get output from the start-runner job
#   runs-on: ubuntu-latest
#   if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#         submodules: 'true'
#     - uses: actions/download-artifact@v3
#       with:
#         name: febio4-${{inputs.os}}-${{inputs.arch}}
#         path: |
#           cmbuild
#     - name: Configure SSH
#       run: |
#         ci/common/linux/configure-ssh.sh
#       env:
#         SSH_USER: ${{ secrets.ssh-user }}
#         SSH_KEY: ${{ secrets.ssh-key }}
#         SSH_HOST: ${{ secrets.ssh-host }}
#     - name: Stage Build to Repo
#       run: |
#         ci/macos/scp-to-repo.sh
#     - name: Make Dev Release
#       run: |
#         ssh repo "python3 update2/FEBioStudio2Dev/makeDevRelease.py -l"
# publish-to-s3:
#   name: Publish to S3
#   needs:
#     - build
#   runs-on: ubuntu-latest
#   if: ${{ always() }}
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#       with:
#         submodules: 'true'
#     - name: Download SDK
#       uses: actions/download-artifact@v3
#       with:
#         name: febio4-sdk-${{inputs.os}}-${{inputs.arch}}
#         path: |
#           artifacts/febio-sdk
#     - name: Download febio
#       uses: actions/download-artifact@v3
#       with:
#         name: febio4-${{inputs.os}}-${{inputs.arch}}
#         path: |
#           artifacts/febio
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1-node16
#       with:
#         aws-access-key-id: ${{ secrets.aws-access-key-id }}
#         aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
#         aws-region: ${{ inputs.aws-region }}
#     - name: Publish to S3
#       env:
#         BUCKET_NAME: febio-packages
#         OS: ${{inputs.os}}
#         REF_NAME: ${{ github.ref_name}}
#         PACKAGE_NAME: febio
#         GIT_TAG: ${{ needs.build.outputs.git_describe }}
#       run: |
#         ci/macos/publish-to-s3.sh
