on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-sdk:
        default: false
        required: false
        type: boolean
      aws-region:
        default: us-east-1
        required: false
        type: string
      os:
        default: macOS
        required: false
        type: string
      arch:
        default: X64
        required: false
        type: string
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
    secrets:
      ssh-user:
        required: true
      ssh-key:
        required: true
      ssh-host:
        required: true
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:

  build:
    name: Clone and build
    runs-on: self-hosted
    outputs:
      git_describe: ${{ steps.git-describe.outputs.git_describe }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: git-describe
        run: |
          echo "git_describe=$(git describe --tags)" >> "$GITHUB_OUTPUT"
      - name: Build
        uses: ./.github/actions/build
        with:
          package-name: ${{ inputs.package-name }}
          script: ci/${{inputs.os}}/build.sh
          os: ${{inputs.os}}
          arch: ${{inputs.arch}}
