on:
  push:
    branches: [ ci/* ]
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
jobs:
  call_workflow:
    uses: febiosoftware/FEBio/.github/workflows/macos-reusable.yml@ci/reusable-workflow-macos
    with:
      runTests: false
