on:
  push:
    branches: [ ci/* ]
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
jobs:
  call_workflow:
    uses: febiosoftware/FEBio/.github/workflows/macos-reusable.yml@ci/reusable-workflow-macos
    with:
      runTests: ${{ inputs.runTests && true || false }}
      package-name: febio4
    secrets:
      ssh-user: ${{ secrets.REPO_USER }}
      ssh-key:  ${{ secrets.REPO_KEY }}
      ssh-host: ${{ secrets.REPO_HOST }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
