on:
  push:
    branches:
      - 'ci/develop'
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: true
        type: boolean
        default: true
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/windows-reusable.yml@develop
    with:
      runTests: ${{ inputs.runTests && true || false }}
      package-name: febio4
      package-sdk: true
      aws-ami-id: ami-0b18c665dbe9efa75
      aws-sg-id: sg-0ca7912782cf1538b
      aws-instance-type: c5a.8xlarge
    secrets: inherit
